# Generated by Django 5.0.6 on 2024-06-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonIDE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrated_development_env',
            name='language',
        ),
    ]
