# Generated by Django 5.0.6 on 2024-08-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='ide',
            field=models.BooleanField(default=False, help_text='When check the code ide with display'),
        ),
    ]
